### ISSUE TITLE
HMMBase v1.0

### ISSUE THREAD

**Issue by junekiwi** [maxmouchet/HMMBase.jl#1]
- [x] Implement the MLE estimator (Distributions::fit_mle! for the M step)
  - [x] Implement `fit_mle!`
  - [x] Implement `fit_mle`
  - [x] Handle multivariate distributions in `mle_step`
  - [x] Test `messages*_log`, `mle_step` and `fit_mle!`
- [x] Cleanup the Viterbi implementation (variable names, ...)
- [x] Benchmark against other implementations (C, Python, hmmlearn, ...) - see #2
- [x] Better tests (in particular check that Viterbi output is correct)
- [x] Compute stationnary distribution (if it exists)
- [x] EM: K-means initialization

**Comment by Thuener** [comment]
Nice work. I use hmmlearn with PyCall in Julia and want to change to HMMBase. Do you have any idea when the Baum-Welch will be added to HMMBase?

**Comment by junekiwi** [comment]
I've added an initial implementation in `v0.0.11`. See the [example](https://maxmouchet.github.io/HMMBase.jl/stable/examples/mle/).

There is room for performance improvements but it works well with univariate distributions (as long as `fit_mle` is implemented for the distribution).

For now, initialization is up to the user.  
And for some reason it does not work with multivariate observations yet. I'll investigate :-)  
*Edit: fixed in `master`*

**Comment by nantonel** [comment]
I've made many changes in my [fork](https://github.com/nantonel/HMMBase.jl).

Let me know if you're interested in a PR: I've changed many things... I apologise for that.
For example I've changed the HMM parameters `\pi0`, `\pi`, `D` to `a` and `A` and `B`.

Baum Welch is now tested and re-written.

There's lot of room for improvement, in particular some choices of `Distributions.jl` are not so well suited for fast updating of the parameters (you have to construct distributions at each iterations and  you could avoid that). But maybe they will change it in the future...
