### ISSUE TITLE
Error in mle.jl?

### ISSUE THREAD

**Issue by mmattocks** [maxmouchet/HMMBase.jl#10]
Hi Max,
I am doing something a bit strange with a fork of this library (I need to learn many HMMs on very large multisequence datasets) here: https://github.com/mmattocks/MS_HMMBase.jl

I am presently writing tests to ensure my modified functions are equivalent to yours. In doing so, I noticed that the following lines in mle.jl appear to have a small indexing error:

```
    new_π = sum(ξ, dims=1)[1,:,:]
    new_π ./= sum(new_π, dims=2)
```

Rabiner 89 has the summation over t to T-1 for xi / gamma, so I think we want ξ[1:end-1,:,:] for the first line. Please let me know if this is incorrect!

Thanks for your work on this library by the way, I've learned a lot from it!

**Comment by junekiwi** [comment]
Hi Mike,

Indeed you're right, thanks :-)

The loop has the right indices:
```julia
for t = 1:T-1, i = 1:K, j = 1:K
   log_ξ[t,i,j] = ...
end
```
but `log_ξ = zeros(T, K, K)` so `log_ξ[T,:,:]` is always equals to 0 (and `ξ[T,:,:]` to 1).

I'll change the dimension of `log_ξ` to `(T-1, K, K)`.
