### ISSUE TITLE
viterbi(hmm, y) got "ERROR: BoundsError: attempt to access T×5 Array{Int64,2} at index [T-1, 0]"

### ISSUE THREAD

**Issue by hanbinlu** [maxmouchet/HMMBase.jl#24]
Hi,

Thank you for the nice work of creating the package. 

I am trying to use the package to first learn the parameters by fit_mle. Then I used the Viterbi function with the learned model and the observations to predict the hidden states. So far I've been able to get the hmm model parameters by following code

```Julia
k = 5
ob_dim = size(zmat, 2)
A = randtransmat(k)
∑ = [MvNormal(rand(ob_dim), ones(ob_dim)) for i = 1:k]
hmm = HMM(A, ∑)
hmm, history = fit_mle(hmm, zmat, display=:final, maxiter=200, init=:kmeans)
```

I first try to decode the observations
```Julia
viterbi(hmm, zmat)
```
I am having the error "ERROR: BoundsError: attempt to access 11823×5 Array{Int64,2} at index [11822, 0]", which 11823 is the number of observations (size(zmat,1) or T).

Then I try to sample another pseudo observations by rand and then Viterbi like in the package document
```Julia
z, y = rand(hmm, 500, seq = true) #ok
viterbi(hmm, y)
```

"ERROR: BoundsError: attempt to access 500×5 Array{Int64,2} at index [499, 0]". I got the "same" err again. I am not sure what's going wrong in my code. I really appreciate your help!

Thanks

**Comment by junekiwi** [comment]
Hi,

Can you try to use the `master` version of HMMBase?
```
pkg> add HMMBase#master
```

Or alternatively, try `viterbi(hmm, y, logl = true)`, to make use of log-likelihoods internally.  
`logl = true` will become the default in the next (v1.1) version.

**Comment by hanbinlu** [comment]
Thank you very much. That solves it!
