### ISSUE TITLE
Application for new maintainer

### ISSUE THREAD

**Issue by gdalle** [maxmouchet/HMMBase.jl#41]
Hi Max!
I saw on the README that your package is looking for a new maintainer, and I feel like I have the ideal background to take care of it.
Right now I'm putting the finishing touches to my doctoral dissertation, but once September comes I should be more available. I'm excited to explore new features for a hypothetical 2.0 version, like compatibility with arbitrary emission distributions or transition structures. It would also be nice to work on compatibility with autodiff for gradient-based estimation.
What do you say?

**Comment by gdalle** [comment]
Ping @maxmouchet :wink:

**Comment by junekiwi** [comment]
Hi Guillaume,

That sounds good to me!  
You're much more active in the Julia ecosystem than me :-)

Honestly I'm open to anything regarding new features.  
Maybe we can have a quick chat to discuss what would be the best way forward?  
Just drop me an email (max@maxmouchet.com) with a tentative date/time. I'm basically available every day in August :-)

**Comment by gdalle** [comment]
Done

**Comment by sparktseung** [comment]
Hey @maxmouchet, @gdalle : It is great to see a potential new maintainer for this package! Can I ask about the current status/progress?

On a less related issue: @maxmouchet What is the current status for Multi-Sequence HMM? The link to MS_HMMBase on README appears to be broken, and I cannot seem to find a related repo.

**Comment by gdalle** [comment]
Hey @sparktseung,
When I took over the package I was really busy with writing my thesis manuscript. Now that I have started a postdoc, I have a bit more time, and should be able to bring it up to speed in the next month or so.
One of the goals will be to merge the interesting features of HMMBase.jl and ControlledHiddenMarkovModels.jl (my own baby), which can handle multiple sequences. Maybe you can check it out in the meantime? https://github.com/gdalle/ControlledHiddenMarkovModels.jl

**Comment by junekiwi** [comment]
We can finally close this, [gdalle/HiddenMarkovModels.jl](https://github.com/gdalle/HiddenMarkovModels.jl) is the successor of HMMBase.jl 🎉
